---
tenant: Silver
ap: "intranet"
epgs:
  - epg: "web"
    encap: "21"
    contract_type: "both"
    consumer: "sql"
    provider: "web"
  - epg: "sql"
    encap: "22"
    contract_type: "provider"
    provider: "sql"
epg_contracts:
  - epg: "web"
    contract: "web"
    contract_type: "provider"
  - epg: "web"
    contract: "sql"
    contract_type: "consumer"
  - epg: "sql"
    contract: "sql"
    contract_type: "provider"




varslist:
  - { tenant: 'MR-TF13DG', vrf: ['MR-TF13DG-vrf'] }
  - { tenant: 'NB-KM13DG', vrf: ['NB-KM13DG-vrf'] }
  - { tenant: 'MH-SC1234', vrf: ['MH-1234-vrf-1', 'MH-1234-vrf-2'], bd: 'MH-SC1234-bd-1' }
  - tenant: 'JS-WV12DW'
    vrf: [ 'JS-WV12DW-vrf-1', 'JS-WV12DW-vrf-2' ]
    bd: 'JS-WV12DW-bd'

  - tenant: 'LC-WV12DW'
    vrf: [ 'LC-WV12DW-vrf-1', 'LC-WV12DW-vrf-2' ]
    bd: 'LC-WV12DW-bd'

  - tenant: 'GOLD'
    vrf: ['GOLD-vrf-1']
    bd: 'GOLD-bd-1'
  
  - tenant: 'GOLD'
    vrf: ['GOLD-vrf-1']
    bd: 'GOLD-bd-1'
    vrf: ['GOLD-vrf-2']
    bd: 'GOLD-bd-2'

varsdict:
  - tenant1:
      vrf: 'vrf-1'
      bd: GOLD-bd-1
  - tenant2:
      vrf: 'vrf-2'
      bd: GOLD-bd-2