---
- name: TOP LEVEL PLAY - CREATE ACI STUFFFFF
  hosts: apic
  connection: local
  gather_facts: False

  tasks:
    - name: ENSURE TENANT EXISTS
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.tenant }}"
        description: "TENANT Created Using Ansible"
      loop: "{{ varslist }}"

    - name: ENSURE TENANT VRF EXISTS
      aci_vrf:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ item.0.tenant }}"
        vrf: "{{ item.1 }}"
        description: "VRF Created Using Ansible"
      loop: "{{ varslist|subelements('vrf') }}"
        
    - name: ENSURE TENANT BRIDGE DOMAIN EXISTS
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ item.0.tenant }}"
        bd: "{{ item.0.bd | default('prod_bd') }}"
        vrf: "{{ item.1 }}"
        description: "BD Created Using Ansible"
      loop: "{{ varslist|subelements('vrf') }}"

    - name: ENSURE TENANT SUBNET EXISTS
      aci_bd_subnet:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ item.0.tenant }}"
        bd: "{{ item.0.bd | default('prod_bd')}}"
        gateway: "10.1.100.1"
        mask: 24
        scope: "public"
        description: "Subnet Created Using Ansible"
      loop: "{{ varslist|subelements('vrf') }}"